spring:
  datasource:
    presto-gateway:
      jdbc-url: jdbc:mysql://datamaster01:3306/presto_gateway
      username: root
      password: 1111
      driver-class-name: com.mysql.cj.jdbc.Driver


#logging:
#  level:
#    personal.leo.presto.gateway.mapper.prestogateway: DEBUG
