spring:
  datasource:
    presto-gateway:
      jdbc-url: jdbc:mysql://localhost:3306/presto_gateway?serverTimezone=Asia/Shanghai
      username: root
      password: 1111
      driver-class-name: com.mysql.cj.jdbc.Driver
